spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/notesystem
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  flyway:
    enabled: false
server:
  port: 8082
omdb:
  base-url: "https://www.omdbapi.com/?apikey={key}&t={title}"
  apikey: "2b28c78a"