spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082
          #jwk-set-uri: http://localhost:8082/oauth2/jwks
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/notesystem
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  flyway:
    enabled: false



server:
  port: 8080
omdb:
  base-url: "https://www.omdbapi.com/?apikey={key}&t={title}"
  apikey: "2b28c78a"